services:
  portfolio-2026:
    build:
      context: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - devops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.dhlabs.cl`)"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
networks:
  devops-network:
    external: true
